user_input1 = input("whats your favorite animal?\n>")
print(user_input1)
user_input2 = input("why is that your favorite animal?\n>")
print(user_input2)
user_input3 = input("where do they live?\n>")
print(user_input3)
user_input4 = input("what is a fun fact about that animal?\n>")
print(user_input4)
print("your favorite animal is " + user_input1 + " because " + user_input2 + " they live in " + user_input3 + " and " + user_input4)