answer1 = int(input("give a whole number that is greater than 6.\n>"))
print(answer1 > 6)
answer2 = int(input("Give a negative number greater than -16.\n>"))
print(answer2 > -16)
answer3 = int(input("give a whole number that is less than 14.\n>"))
print(answer3 < 14)
answer4 = int(input("give a whole number that is equal to 69.\n>"))
print(answer4 == 69)
answer5 = int(input("give a whole number that is greater than or equal to 15.\n>"))
print(answer5 >= 15)